- name: Install Docker, Immich, Restic, Certbot and Caddy
  hosts: localhost
  become: true
  vars_files:
    - secret_vars.yml
  roles:
    - docker
    - immich
    - certbot
    - caddy
    - restic
