---

- name: Get Caddy gpg key
  ansible.builtin.uri:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    return_content: true
  register: caddy_gpg

- name: Add Caddy Repo
  deb822_repository:
    name: caddy
    types: deb
    uris: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
    suites: any-version
    components:
      - main
    signed_by: "{{ caddy_gpg.content }}"

- name: Get XCaddy gpg key
  ansible.builtin.uri:
    url: https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key
    return_content: true
  register: xcaddy_gpg

- name: Add XCaddy Repo
  deb822_repository:
    name: xcaddy
    types: deb
    uris: https://dl.cloudsmith.io/public/caddy/xcaddy/deb/debian
    suites: any-version
    components:
      - main
    signed_by: "{{ xcaddy_gpg.content }}"

- name: Install Go, Caddy and XCaddy
  ansible.builtin.apt:
    update_cache: true
    name:
      - golang-go
      - caddy
      - xcaddy

- name: Build Caddy with the Metaname extension
  ansible.builtin.command:
    argv:
      - xcaddy
      - build 
      - --with 
      - github.com/caddy-dns/metaname
      - --output
      - /usr/bin/caddy
  notify: Caddy Restart

- name: Configure Caddy
  ansible.builtin.template:
    dest: /etc/caddy/Caddyfile
    src: templates/Caddyfile.jinja
  notify: Caddy Restart