---

    - name: Install packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-dev
          - python3-venv
          - python3-virtualenv
          - libaugeas-dev
          - gcc

    - name: Create virtual env for certbot
      ansible.builtin.pip:
        virtualenv: /opt/certbot
        name:
          - certbot
          - git+https://github.com/metaname/certbot-dns-metaname.git

    - name: Create certbot conf file
      ansible.builtin.template:
        dest: /etc/metaname.ini
        src: templates/metaname.ini.jinja
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Create a certificate
      ansible.builtin.command:
        argv:
          - /opt/certbot/bin/certbot
          - --dns-metaname-credentials
          - /etc/metaname.ini
          - certonly
          - --authenticator 
          - dns-metaname
          - --non-interactive
          - --domain 
          - photos.jarvis.kiwi.nz
